<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : ibrahim69
// Last edited date : Fri, 03 Nov 2017 09:06:25 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Pengumuman Forum';
$l['announcements'] = 'Pengumuman';
$l['forum_announcement'] = 'Pengumuman Forum:{1}';
$l['error_invalidannouncement'] = 'Pengumuman yang dimaksud tidak valid.';
$l['announcement_edit'] = ' Ubah pengumuman ini';
$l['announcement_qdelete'] = 'Hapus pengumuman ini';
$l['announcement_quickdelete_confirm'] = 'Apakah Anda yakin akan menghapus pengumuman ini?';
