<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : ibrahim69
// Last edited date : Fri, 03 Nov 2017 09:14:50 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Versi Penuh:';
$l['archive_replies'] = 'Balasan-balasan';
$l['archive_reply'] = 'Balasan';
$l['archive_pages'] = 'Halaman:';
$l['archive_note'] = 'Anda sedang melihat tampilan versi penjabaran ke bawah dari konten kami.  <a href="{1}">Lihat tampilan versi penuh</a> dengan format yang lebih baik.';
$l['archive_nopermission'] = 'Maaf tetapi Anda tidak memiliki izin untuk mengakses sumber ini.';
$l['error_nothreads'] = 'Sedang tidak ada thread pada forum ini.';
$l['error_nopermission'] = 'Maaf tetapi Anda tidak memiliki izin untuk mengakses sumber ini. 
';
$l['error_unapproved_thread'] = 'Thread ini tidak disetujui Silakan <a href="{1}"> melihat versi lengkap </a> untuk melihat isi thread ini.
';
$l['archive_not_found'] = ' <h1>Tidak Ditemukan 404</h1><p>Dokumen yang dimaksud tidak ditemukan pada server ini.</p>';
$l['error_mustlogin'] = 'Papan buletin ini mengharuskan semua pengguna untuk masuk.
';
