<?php
/**
 * MyBB 1.8 English Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

$l['nav_online'] = "Siapa Yang Online";
$l['nav_onlinetoday'] = "Siapa Yang Telah Online Hari Ini";

$l['viewing_announcements'] = "Menampilkan Pengumuman <a href=\"{1}\">{2}</a>";
$l['viewing_announcements2'] = "Menampilkan Pengumuman Forum";
$l['viewing_attachment'] = "Menampilkan Attachment";
$l['viewing_attachment2'] = "Menampilkan <a href=\"attachment.php?aid={1}\" target=\"_blank\">Attachment</a> pada Thread <a href=\"{3}\">{2}</a>";
$l['viewing_calendar'] = "Menampilkan <a href=\"calendar.php\">Kalender</a>";
$l['viewing_event'] = "Menampilkan Acara";
$l['viewing_event2'] = "Menampilkan Acara <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">Menambahkan Acara</a>";
$l['editing_event'] = "Mengubah Acara";
$l['viewing_contact_us'] = "Menampilkan <a href=\"contact.php\">Kontak Kami</a>";
$l['editing_post'] = "Mengubah Posting";
$l['viewing_forum'] = "Menampilkan Forum";
$l['viewing_forum2'] = "Menampilkan Forum <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "Dialihkan ke <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">Indeks Utama</a>";
$l['activating_account'] = "MengaktifkanAccount";
$l['viewing_profile'] = "Menampilkan Profil";
$l['viewing_profile2'] = "Menampilkan Profil Dari <a href=\"{1}\">{2}</a>";
$l['registering'] = "<a href=\"member.php?action=register\">Mendaftarkan</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">Masuk</a>";
$l['logging_in_plain'] = "Masuk";
$l['logging_out'] = "Keluar";
$l['emailing_user'] = "Meng-email Pengguna";
$l['rating_user'] = "Me-rating Pengguna";
$l['viewing_memberlist'] = "Menampilkan <a href=\"memberlist.php\">Daftar Anggota</a>";
$l['viewing_whoposted'] = "Menampilkan Pembuat Posting";
$l['viewing_whoposted2'] = "Menampilkan Pembuat Posting Pada Thread <a href=\"{1}\">{2}</a>";
$l['marking_read'] = "<a href=\"misc.php?action=markread\">Menandai Forum Telah Dibaca</a>";
$l['viewing_helpdocs'] = "Menampilkan <a href=\"misc.php?action=help\">Dokumen Bantuan</a>";
$l['viewing_buddylist'] = "Menampilkan <a href=\"misc.php?action=buddypopup\">Daftar Teman</a>";
$l['viewing_smilies'] = "Menampilkan <a href=\"misc.php?action=smilies\">Daftar Smilie</a>";
$l['viewing_syndication'] = "Menampilkan <a href=\"misc.php?action=syndication\">Sindikasi RSS</a> Page";
$l['replying_thread'] = "Membalas Thread";
$l['replying_thread2'] = "Membalas Thread <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "Melakukan Posting Thread Baru";
$l['posting_thread2'] = "Melakukan Posting Thread Baru Pada <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "Menampilkan <a href=\"online.php\">Siapa Yang Online</a>";
$l['viewing_woltoday'] = "Menampilkan <a href=\"online.php?action=today\">Siapa Yang Telah Online Hari Ini</a>";
$l['creating_poll'] = "Membuat Polling Baru";
$l['editing_poll'] = "Mengubah Polling";
$l['viewing_pollresults'] = "Menampilkan Hasil Polling";
$l['voting_poll'] = "Memberi Suara Pada Polling";
$l['using_modtools'] = "Menggunakan Tool Moderator";
$l['sending_pm'] = "Mengirim Pesan Pribadi";
$l['reading_pm'] = "Membaca Pesan Pribadi";
$l['editing_pmfolders'] = "Mengubah Folder PM";
$l['using_pmsystem'] = "Menggunakan Sistem PM";
$l['reporting_post'] = "Melaporkan Posting";
$l['searching_forum'] = "<a href=\"search.php\">Mencari</a> {1}";
$l['reading_thread'] = "Baca Thread";
$l['reading_thread2'] = "baca Thread <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "Menampilkan Tim Forum";
$l['viewing_stats'] = "Menampilkan Statistik Forum";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">Memperbarui Profil</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">Pilihan Memperbarui</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">Mengubah Tanda Tangan</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">Mengubah Avatar</a>";
$l['viewing_subscriptions'] = "Menampilkan <a href=\"usercp.php?action=subscriptions\">Langganan Thread</a>";
$l['viewing_favorites'] = "Menampilkan <a href=\"usercp.php?action=favorites\">Thread Favorit</a>";
$l['editing_pad'] = "Mengubah <a href=\"usercp.php?action=notepad\">Pad Pribadi</a>";
$l['editing_password'] = "Mengubah <a href=\"usercp.php?action=password\">Password</a>";
$l['user_cp'] = "Menampilkan <a href=\"usercp.php\">Control Panel Pengguna</a>";
$l['viewing_portal'] = "Menampilkan <a href=\"portal.php\">Portal</a> Page";
$l['viewing_noperms'] = "Menampilkan Halaman Tanpa Izin";
$l['unknown_location'] = "<a href=\"{1}\">Lokasi Tidak Diketahui</a>";
$l['giving_reputation'] = "Memberi Reputasi";
$l['member_resendactivation'] = "Mengirim Kembali Email Aktivasi Account";
$l['member_lostpw'] = "Menerima <a href=\"member.php?action=lostpw\">Password Yang Hilang</a>";
$l['sending_thread'] = "Mengirim thread ke teman";
$l['guest'] = "Tamu";
$l['page'] = "Halaman";
$l['users_online'] = "Siapa Yang Online";
$l['on_username'] = "Username";
$l['time'] = "Waktu";
$l['location'] = "Lokasi";
$l['online_today'] = "Siapa Yang Telah Online Hari Ini";
$l['refresh_page'] = "Refresh Halaman Ini";
$l['online_online_plural'] = "pengguna";
$l['online_online_singular'] = "pengguna";
$l['online_member_plural'] = "anggota";
$l['online_member_singular'] = "anggota";
$l['online_anon_plural'] = "adalah";
$l['online_anon_singular'] = "adalah";
$l['online_guest_plural'] = "tamu";
$l['online_guest_singular'] = "tamu";
$l['online_count'] = "{1} {2} aktif pada {3} menit terakhir({4} {5}, {6} dari {7} tidak terlihat, dan {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Nama Host:";
$l['if_resolvable'] = "(jika dapat dipisahkan)";
$l['admin_options'] = "Pilihan Admin:";
$l['search_regip_users'] = "Cari pengguna yang telah terdaftar menggunakan IP ini";
$l['search_postip_users'] = "Cari pengguna yang telah melakukan posting dengan IP ini";
$l['lookup'] = "[lookup]";
$l['member_online_today'] = "<strong>1</strong> Anggota Yang Telah Online Hari Ini";
$l['members_were_online_today'] = "<strong>{1}</strong> Anggota Yang Telah Online Hari Ini";
$l['member_online_hidden'] = " ({1} anggota tidak terlihat)";
$l['members_online_hidden'] = " ({1} anggota-anggota tidak terlihat)";
$l['rating_thread'] = "Rating thread";
$l['viewing_imcenter'] = "Tampilkan Pusat IM";
$l['managing_favorites'] = "Menglola Threads favorit";
$l['managing_subscriptions'] = "Mengelola Thread Langganan";
$l['managing_group'] = "Mengelola Pengguna Group";
$l['viewing_modcp'] = "Menampilkan CP Moderator";
$l['viewing_modlogs'] = "Menampilkan Log Moderator";
$l['managing_announcements'] = "Mengelola Pengumuman";
$l['search_for_user'] = "Mencari pengguna";
$l['managing_warninglogs'] = "Mengelola Log Peringatan";
$l['searching_ips'] = "Mencari IP";
$l['viewing_reports'] = "Menampilkan Posting Yang Dilaporkan";
$l['adding_announcement'] = "Menambah Pengumuman";
$l['deleting_announcement'] = "Menghapus Pengumuman";
$l['editing_announcement'] = "Mengubah Pengumuman";
$l['managing_modqueue'] = "Mengelola Antrian Moderasi";
$l['editing_user_profiles'] = "Mengubah Profil Pengguna";
$l['managing_bans'] = "Mengelola Larangan";
$l['revoking_warning'] = "Menarik kembali peringatan";
$l['warning_user'] = "Memberi peringatan pengguna";
$l['viewing_warning'] = "Menampilkan peringatan";
$l['managing_warnings'] = "Mengelola peringatan";
$l['changing_dst'] = "Mengubah Pengubah DST";
$l['printing_thread'] = "Mencetak Thread";
$l['printing_thread2'] = "Mencetak Thread <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Mengelola Daftar Teman/Abaikan";
